# See these links:
# - https://github.com/PHPirates/travis-ci-latex-pdf#tectonic-docker
# - https://github.com/japaric/trust
# - https://malramsay.com/post/compiling_latex_on_travis/

dist: bionic
sudo: required
language: generic
services: docker

# TODO: Update the following to install extra dependencies if needed
before_install:
  - sudo apt-get install python-pygments # If you use the minted package
  - sudo apt-get install p7zip-full # If you want to archive your project files
# - sudo apt-get install ghostscript # If you use latex > dvips > ps2pdf
## If you use custom fonts:
# - mkdir $HOME/.fonts
# - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
# - fc-cache -f -v

install:
  - source ci/texlive/texlive_install.sh

script:
# TODO: Change the following to compile the correct file(s)
  # Texliveonfly will download packages automatically
  # You can use latexmk to automatically handle bibtex and references (recommended)
  - texliveonfly --compiler=latexmk --arguments='-pdf -bibtex -shell-escape -synctex=1 -interaction=nonstopmode' main.tex

  # But you could use any other compiler (pdflatex, bibtex, pdflatex - have to do 2 times)
  # as well instead of latexmk.

## Uncomment the following lines to see the packages installed in travis
after_script:
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  - tlmgr list --only-installed | grep -oP 'i \K.+?(?=:)'

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  # TODO update `api_key.secure`
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789 --pro`
  # - Paste the output down here
  api_key:
    secure: "MqfQHdwYilqUlnp469KLYXRoacmxLxRwSkuLreWc+awIsSjS/etgCDhsLmY+yGQ91jKzrxFGRWsqCT9z7jfwE/li/lxQ/J5SRUfnK0PICfFjVL+Lb8t7w4C0MtMaWdoftBElsx90O7YGXoR2pzCUrUwKZA8hqFKqoOepFjvyeGKW7jNkoUEcEOk7lLkHHw64TUqK2TDmnU3oJUeg8GdUmHgEx0vOGEWRfxJZqlh/vY/Ee/IFFBYsYelR5ARJ2KwR036+kAczc0SCRyE1dIrOPCNq8LDUhKd59nJP3w1x0k+VssKpmz+Etoce20VOkGTmf9VL3Pmz+2ipJ3skIHYrooIV4bsA/huyAi4dmJMil/dVyFbwSYkN9+vmJK75Fd99nJ9CzOuGZ5GG2Jt5y4OSGuqQ4NvZY1fCzD0QMBkpkN1Jur6TNiY4q4Pv8HS4pB7r91JqxnYZEVDtxL97aRi6sON1v1TplKEtxxwYX2hU3P+XEsAhgHJNZiXWESu0c9g86xA3SLcdzWg4dToJ1f0gsN6OIPcVFK4VyNxwy/3u1cxE10RQWOwnBWMK2MU3JAF7LBonPIM6WoQjscA+Yl/+47zqCsh3Sur7sjzWJSDpCF2+4A9Mwr2CwBpdIngpt0XXhbliHwBfjj/7BYHH5Q2ZD+ZdxlFNnxt0VcHMoQLScqo="
  # TODO: Make change here to deploy the right artifacts
  file_glob: true
  file:
    - ./*.pdf
    - ./*.7z
  on:
    condition: $DEPLOY = never
    tags: true
  provider: releases
  skip_cleanup: true

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.texlive
  - chmod -R a+r /tmp/texlive

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never